feat: add code examples
openearthplatforminitiative/flood-api pull request #12
Opened 2023-12-07 15:02 UTC by giltinde

The following appears in the terminal when running locally:
```
INFO:     127.0.0.1:50537 - "GET /9e68c24da9f5fd56991c.worker.js.map HTTP/1.1" 404 Not Found
```
But it's maybe not an issue: https://github.com/Redocly/redoc/issues/1240

2023-12-08 12:02 UTC, dymbe commented
> The following appears in the terminal when running locally:
> 
> ```
> INFO:     127.0.0.1:50537 - "GET /9e68c24da9f5fd56991c.worker.js.map HTTP/1.1" 404 Not Found
> ```
> 
> But it's maybe not an issue: [Redocly/redoc#1240](https://github.com/Redocly/redoc/issues/1240)

It's normal if it only happens when you have to console open

2023-12-12 07:44 UTC, kstigen requested changes

2023-12-12 07:44 UTC, kstigen commented on flood_api/example_code/curl/detailed.sh
> +curl -i -X GET $api_url$api_path?min_lon=22.0&max_lon=23.05&min_lat=4.764412&max_lat=5.015732
Add newlines in all files

2023-12-12 07:44 UTC, kstigen commented on flood_api/openapi/openapi.py
> +                                api_url=f"{settings.api_url}",
We can simplify all the example-code files by concatenating `api_url` and `api_path` here.

2023-12-12 07:44 UTC, kstigen commented on flood_api/example_code/python/threshold.py
> +        url="$api_url$api_path", params={"lon": 22.260536, "lat": 4.882569}
Simplify all the example-code files by only requiring a single parameter to be replaced. Rename to `endpoint_url`. See comment in `openapi.py`

2023-12-12 07:44 UTC, kstigen commented on flood_api/openapi/openapi.py
> +        title="Geocoder API",
Copy-paste error

2023-12-12 07:44 UTC, kstigen commented on flood_api/openapi/openapi.py
> +        "url": "https://api-test.openepi.io/assets/icons/open-epi-logo.svg"
See weather-api for how to construct an url to given environment

2023-12-12 07:44 UTC, kstigen commented on flood_api/__main__.py
> +        title="Geocoder API",
Copy-paste error

2023-12-12 07:44 UTC, kstigen commented on flood_api/__main__.py
>      version=settings.version,
`version` and `description` are redundant here, as we redefine them in `openapi.py`. Can be removed

2023-12-19 09:33 UTC, merged